#!/usr/bin/env python3
"""Synthetic FC-v1 fixture generator (spike protocol: backlog/pi/11_spike_briefs.md §1).

Emits the PRE-BAA, fully-synthetic corpus that feeds the S1 OCR bake-off and (later) the
S2 extraction spike. NOTHING here touches live PHI — every page is drawn from fixed
templates with a synthetic patient ("Jane Sample") and a fixed provider roster.

What it generates under ``<out>/fc_v1_synthetic/``:

  * FC-1  — clean typed EMR-style visit notes (text-layer fast path). For EVERY page it
            also writes the GOLD transcript ``gold/<page_id>.txt`` containing exactly the
            strings drawn onto that page: the generator IS the gold labeler for synthetic
            pages, so the S1 scorer has ground truth for free.
  * FC-B  — CMS-1500-ish itemized bills: header + a drawn line-item table. Alongside each
            PDF, the gold cell grid is written as ``tables/<doc_id>.csv`` (exact strings;
            dollar cells exact to the cent). Line amounts are integer cents internally and
            rendered with integer formatting — never float math (money discipline).
  * FC-2/FC-3 — cannot be generated in software (they require real fax/scan hardware and
            founder-filled forms). This script emits their print-ready SOURCE PDFs plus a
            ``print_sources/README.txt`` explaining the §1 physical protocol, and two
            checkbox/intake-form source PDFs for FC-3.
  * MANIFEST.json — per-file {set, page_count, sha256, seed}; the brief's freeze-as-FC-v1
            discipline (additions create FC-v2, never silent drift).

Determinism: a single ``random.Random(seed)`` drives all sampling. No global ``random``,
no wall-clock. Same seed + sizes => byte-identical PDFs => identical MANIFEST hashes.

Ownership: M1 Wave D spike S1 tool. Lives under backend/scripts/ (not a package); not
imported by app.*.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import random
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# --- Fixed synthetic rosters (no real people; deterministic sampling only) -------------
_PROVIDERS = (
    "Dr. Alex Rivera",
    "Dr. Morgan Patel",
    "Dr. Sydney Okafor",
    "Dr. Casey Nguyen",
    "Dr. Jordan Blake",
)
_FACILITIES = (
    "Riverbend Family Clinic",
    "Northgate Urgent Care",
    "Summit Orthopedics",
    "Lakeside Imaging Center",
)
_CHIEF_COMPLAINTS = (
    "low back pain after motor vehicle collision",
    "neck stiffness and headache",
    "right shoulder pain with limited range of motion",
    "bilateral knee pain following rear-end collision",
)
_EXAM_LINES = (
    "Vitals within normal limits. Alert and oriented x3.",
    "Tenderness on palpation of the paraspinal muscles.",
    "Reduced range of motion; strength 4/5 in affected limb.",
    "No acute distress. Gait antalgic on the right.",
)
_ASSESSMENTS = (
    "Cervical strain (S13.4XXA).",
    "Lumbar sprain (S33.5XXA).",
    "Contusion of shoulder (S40.011A).",
    "Knee sprain (S83.90XA).",
)
_PLANS = (
    "Physical therapy 2x weekly for 4 weeks. Ibuprofen 600mg PRN.",
    "Referral to orthopedics. MRI of affected joint ordered.",
    "Home exercise program. Follow up in 2 weeks.",
    "Continue conservative management. Re-evaluate in 10 days.",
)

# CMS-1500-ish billing line templates: (cpt, description, cents). Amounts are integer
# cents — the money-engine ground truth is cent-exact by construction.
_BILL_LINES = (
    ("99213", "Office visit, established patient", 18500),
    ("72148", "MRI lumbar spine without contrast", 142000),
    ("97110", "Therapeutic exercise, per 15 min", 4500),
    ("73030", "X-ray shoulder, complete", 9800),
    ("99204", "Office visit, new patient", 32500),
    ("97140", "Manual therapy, per 15 min", 5200),
    ("72141", "MRI cervical spine without contrast", 138000),
    ("20550", "Injection, tendon sheath", 21000),
)

_FONT = "Helvetica"
_FONT_BOLD = "Helvetica-Bold"


def _fmt_dollars(cents: int) -> str:
    """Render integer cents as ``$1,234.56`` with NO float math.

    Uses integer division/modulo for the dollars/cents split, then comma-groups the dollar
    part by hand. A wrong cent here would fail an S1 table cell, so this must be exact.
    """
    dollars, remainder = divmod(cents, 100)
    return f"${dollars:,}.{remainder:02d}"


@dataclass(frozen=True)
class _ManifestEntry:
    set_name: str
    page_count: int
    sha256: str
    seed: int


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _gold_header(generator: str) -> str:
    """Provenance banner prepended to every gold transcript (auditable, synthetic)."""
    return (
        f"# generated by {generator}, synthetic, no PHI\n"
        f"# gold transcript — exact strings drawn on the corresponding page\n"
    )


# --------------------------------------------------------------------------------------
# PDF drawing helpers (deterministic; no timestamps => reproducible bytes)
# --------------------------------------------------------------------------------------
def _new_canvas() -> tuple[canvas.Canvas, io.BytesIO]:
    """A reportlab canvas writing to an in-memory buffer.

    ``invariant=1`` strips the PDF's producer/creation-date metadata so identical draw
    calls yield byte-identical output — the determinism the freeze discipline needs.
    """
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter, invariant=1)
    pdf.setTitle("FC-v1 synthetic fixture")
    return pdf, buffer


def _write_pdf(buffer: io.BytesIO, path: Path) -> None:
    path.write_bytes(buffer.getvalue())


# --------------------------------------------------------------------------------------
# FC-1: clean EMR visit notes + gold transcripts
# --------------------------------------------------------------------------------------
def _emr_page_lines(rng: random.Random, page_index: int) -> list[str]:
    """The exact text lines for one FC-1 page (drives BOTH the PDF and its gold file)."""
    provider = rng.choice(_PROVIDERS)
    facility = rng.choice(_FACILITIES)
    complaint = rng.choice(_CHIEF_COMPLAINTS)
    exam = rng.choice(_EXAM_LINES)
    assessment = rng.choice(_ASSESSMENTS)
    plan = rng.choice(_PLANS)
    # Synthetic, stable date; never wall-clock.
    dos_day = 1 + (page_index % 27)
    return [
        f"PATIENT: Jane Sample    DOB: 1985-03-14    MRN: SYNTH-{page_index:04d}",
        f"DATE OF SERVICE: 2024-02-{dos_day:02d}    PROVIDER: {provider}",
        f"FACILITY: {facility}",
        "CHIEF COMPLAINT",
        complaint,
        "HISTORY",
        "Patient reports symptoms began following a motor vehicle collision.",
        "EXAM",
        exam,
        "ASSESSMENT",
        assessment,
        "PLAN",
        plan,
    ]


def _emit_fc1(rng: random.Random, out_root: Path, pages: int, seed: int) -> list[_ManifestEntry]:
    fc1_dir = out_root / "fc1_clean_emr"
    gold_dir = fc1_dir / "gold"
    fc1_dir.mkdir(parents=True, exist_ok=True)
    gold_dir.mkdir(parents=True, exist_ok=True)

    entries: list[_ManifestEntry] = []
    generator = "generate_fc_fixtures.py"
    for i in range(pages):
        page_id = f"fc1_p{i:04d}"
        text_lines = _emr_page_lines(rng, i)

        pdf, buffer = _new_canvas()
        y = 720
        for line in text_lines:
            # Section headers (CHIEF COMPLAINT / HISTORY / EXAM / ASSESSMENT / PLAN) render bold.
            is_header = line in {"CHIEF COMPLAINT", "HISTORY", "EXAM", "ASSESSMENT", "PLAN"}
            pdf.setFont(_FONT_BOLD if is_header else _FONT, 13 if is_header else 11)
            pdf.drawString(72, y, line)
            y -= 26
        pdf.showPage()
        pdf.save()
        pdf_path = fc1_dir / f"{page_id}.pdf"
        _write_pdf(buffer, pdf_path)

        # Gold transcript: provenance header + exactly the strings drawn on the page.
        gold_path = gold_dir / f"{page_id}.txt"
        gold_path.write_text(
            _gold_header(generator) + "\n".join(text_lines) + "\n", encoding="utf-8"
        )

        entries.append(_ManifestEntry("FC-1", 1, _sha256(pdf_path), seed))
    return entries


# --------------------------------------------------------------------------------------
# FC-B: CMS-1500-ish itemized bills + gold cell grids
# --------------------------------------------------------------------------------------
def _bill_grid(rng: random.Random, doc_index: int) -> list[list[str]]:
    """The gold cell grid for one FC-B bill: header row + line rows + total row.

    Columns: Date of Service | CPT | Description | Billed. Dollar cells are cent-exact
    strings; the total is an integer-cents sum, never float-accumulated.
    """
    n_lines = 3 + (doc_index % 3)  # 3..5 line items, deterministic
    chosen = [_BILL_LINES[(doc_index + k) % len(_BILL_LINES)] for k in range(n_lines)]

    grid: list[list[str]] = [["Date of Service", "CPT", "Description", "Billed"]]
    total_cents = 0
    for k, (cpt, desc, cents) in enumerate(chosen):
        dos_day = 1 + ((doc_index + k) % 27)
        grid.append([f"2024-03-{dos_day:02d}", cpt, desc, _fmt_dollars(cents)])
        total_cents += cents  # integer cents only
    grid.append(["", "", "TOTAL", _fmt_dollars(total_cents)])
    return grid


def _emit_fcb(rng: random.Random, out_root: Path, docs: int, seed: int) -> list[_ManifestEntry]:
    fcb_dir = out_root / "fcb_bills"
    tables_dir = fcb_dir / "tables"
    fcb_dir.mkdir(parents=True, exist_ok=True)
    tables_dir.mkdir(parents=True, exist_ok=True)

    entries: list[_ManifestEntry] = []
    for i in range(docs):
        doc_id = f"fcb_b{i:04d}"
        grid = _bill_grid(rng, i)

        pdf, buffer = _new_canvas()
        pdf.setFont(_FONT_BOLD, 14)
        pdf.drawString(72, 740, "ITEMIZED STATEMENT (CMS-1500 style)")
        pdf.setFont(_FONT, 11)
        pdf.drawString(72, 720, f"Patient: Jane Sample    Account: SYNTH-BILL-{i:04d}")
        pdf.drawString(72, 704, "Facility: Riverbend Family Clinic")

        # Draw the grid as a simple fixed-column table.
        col_x = (72, 190, 260, 470)
        y = 670
        for row in grid:
            for cell, x in zip(row, col_x, strict=False):
                pdf.setFont(_FONT_BOLD if y == 670 or cell == "TOTAL" else _FONT, 11)
                pdf.drawString(x, y, cell)
            y -= 22
        pdf.showPage()
        pdf.save()
        pdf_path = fcb_dir / f"{doc_id}.pdf"
        _write_pdf(buffer, pdf_path)

        # Gold cell grid: exact strings, dollar cells exact.
        csv_path = tables_dir / f"{doc_id}.csv"
        with csv_path.open("w", encoding="utf-8", newline="") as handle:
            csv.writer(handle).writerows(grid)

        entries.append(_ManifestEntry("FC-B", 1, _sha256(pdf_path), seed))
    return entries


# --------------------------------------------------------------------------------------
# FC-2 / FC-3: print-source PDFs + physical-protocol instructions
# --------------------------------------------------------------------------------------
_PRINT_SOURCES_README = """\
FC-2 / FC-3 physical-protocol sources (backlog/pi/11_spike_briefs.md §1)
=======================================================================

These sets CANNOT be produced in software — they require real fax/scan hardware and
founder-filled forms to reproduce authentic degradation. This directory holds the
print-ready SOURCE material; the degraded fixtures are produced by hand, then dropped
back into the FC-v1 corpus.

no live PHI: every source here is synthetic ("Jane Sample").

FC-2 (degraded mixed — the make-or-break OCR set):
  1. Print a stratified subset of the FC-1 clean pages (see ../fc1_clean_emr/).
  2. Fax and/or rescan them on real hardware at low DPI; introduce skew, stamps, and
     margin handwriting to reproduce fax artifacts.
  3. Scan the results back to PDF/TIFF — those scans ARE FC-2.
  4. Gold-label a 10% stratified page sample (stratified across noise levels, not
     first-N). Record each gold label's provenance (who transcribed it, source page);
     ambiguous tokens are adjudicated by the legal cofounder and the ruling recorded.

FC-3 (handwritten + checkbox forms):
  1. Print the intake/checkbox source PDFs in this directory (fc3_intake_source_*.pdf).
  2. Founders fill them in by hand (synthetic answers only — no real patients).
  3. Scan the filled forms — those scans ARE FC-3.
  4. Gold-label handwriting + checkbox state; record provenance as above.

Freeze discipline: once produced, FC-2/FC-3 pages join FC-v1 with MANIFEST entries.
Later additions create FC-v2 — never silent drift into FC-v1.
"""


def _emit_fc3_intake_source(pdf_path: Path) -> None:
    """A synthetic checkbox/intake form: labeled checkboxes + blank write-in lines."""
    pdf, buffer = _new_canvas()
    pdf.setFont(_FONT_BOLD, 14)
    pdf.drawString(72, 740, "PATIENT INTAKE FORM (synthetic — no PHI)")
    pdf.setFont(_FONT, 11)
    pdf.drawString(72, 716, "Name: ____________________________   Date: ______________")
    pdf.drawString(72, 692, "Reason for visit (check all that apply):")

    checkbox_items = (
        "Motor vehicle collision",
        "Slip and fall",
        "Neck pain",
        "Back pain",
        "Headache",
        "Numbness / tingling",
    )
    y = 668
    for item in checkbox_items:
        pdf.rect(72, y - 2, 10, 10, stroke=1, fill=0)  # empty checkbox to be filled by hand
        pdf.drawString(90, y, item)
        y -= 22

    pdf.drawString(72, y - 10, "Pain level (0-10): ______")
    pdf.drawString(72, y - 34, "Additional notes:")
    for offset in range(3):
        line_y = y - 58 - offset * 20
        pdf.line(72, line_y, 520, line_y)
    pdf.showPage()
    pdf.save()
    _write_pdf(buffer, pdf_path)


def _emit_print_sources(out_root: Path, seed: int) -> list[_ManifestEntry]:
    src_dir = out_root / "print_sources"
    src_dir.mkdir(parents=True, exist_ok=True)
    (src_dir / "README.txt").write_text(_PRINT_SOURCES_README, encoding="utf-8")

    entries: list[_ManifestEntry] = []
    for i in range(2):  # two FC-3 intake source forms
        pdf_path = src_dir / f"fc3_intake_source_{i:02d}.pdf"
        _emit_fc3_intake_source(pdf_path)
        entries.append(_ManifestEntry("FC-3", 1, _sha256(pdf_path), seed))
    return entries


# --------------------------------------------------------------------------------------
# Manifest + orchestration
# --------------------------------------------------------------------------------------
def _write_manifest(out_root: Path, entries_by_file: dict[str, _ManifestEntry], seed: int) -> Path:
    """Write MANIFEST.json: sorted per-file records + a seed/summary header.

    Keys are POSIX-relative paths under the FC-v1 root so the manifest is stable across
    machines. Sorted for byte-stable output (determinism proof relies on this).
    """
    files = {
        rel: {
            "set": entry.set_name,
            "page_count": entry.page_count,
            "sha256": entry.sha256,
            "seed": entry.seed,
        }
        for rel, entry in sorted(entries_by_file.items())
    }
    manifest = {
        "corpus": "FC-v1",
        "generator": "generate_fc_fixtures.py",
        "seed": seed,
        "synthetic": True,
        "phi": False,
        "file_count": len(files),
        "files": files,
    }
    manifest_path = out_root / "MANIFEST.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest_path


def generate(out: Path, fc1_pages: int, fcb_docs: int, seed: int) -> Path:
    """Generate the full FC-v1 synthetic corpus under ``out/fc_v1_synthetic/``.

    Returns the MANIFEST.json path. Deterministic in (seed, fc1_pages, fcb_docs).
    """
    rng = random.Random(seed)
    out_root = out / "fc_v1_synthetic"
    out_root.mkdir(parents=True, exist_ok=True)

    entries_by_file: dict[str, _ManifestEntry] = {}

    def _record(entries: list[_ManifestEntry], subdir: str, prefix: str, ext: str) -> None:
        for idx, entry in enumerate(entries):
            rel = f"{subdir}/{prefix}{idx:04d}.{ext}"
            entries_by_file[rel] = entry

    # Draw FC-1 first, then FC-B, then print sources — fixed order keeps the shared rng
    # stream deterministic across the whole corpus.
    fc1_entries = _emit_fc1(rng, out_root, fc1_pages, seed)
    _record(fc1_entries, "fc1_clean_emr", "fc1_p", "pdf")

    fcb_entries = _emit_fcb(rng, out_root, fcb_docs, seed)
    _record(fcb_entries, "fcb_bills", "fcb_b", "pdf")

    print_entries = _emit_print_sources(out_root, seed)
    for idx, entry in enumerate(print_entries):
        entries_by_file[f"print_sources/fc3_intake_source_{idx:02d}.pdf"] = entry

    return _write_manifest(out_root, entries_by_file, seed)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the FC-v1 synthetic OCR fixture corpus (no PHI). FC-1 clean EMR + "
            "FC-B bills are fully generated with gold labels; FC-2/FC-3 print-source PDFs "
            "and a physical-protocol README are emitted for hardware degradation."
        )
    )
    parser.add_argument("--out", required=True, type=Path, help="output directory")
    parser.add_argument(
        "--fc1-pages", type=int, default=30, help="FC-1 clean EMR pages (full run: 300)"
    )
    parser.add_argument(
        "--fcb-docs", type=int, default=4, help="FC-B itemized-bill documents (full run: ~80)"
    )
    parser.add_argument("--seed", type=int, default=1729, help="deterministic RNG seed")
    args = parser.parse_args(argv)

    manifest_path = generate(args.out, args.fc1_pages, args.fcb_docs, args.seed)
    print(f"wrote {manifest_path}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
